global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'python-exporter'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'ml-anomaly-api'
    static_configs:
      - targets: ['host.docker.internal:5001']

rule_files:
  - "alert.rules.yml"
